version: '3.9'

services:
  admin-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "admin-frontend"
    ports:
      - "5173:5173" 
    volumes:
      - .:/app
      - /app/node_modules # tránh ghi đè node_modules trong container
    environment:
      - CHOKIDAR_USEPOLLING=true # fix hot reload trong Docker
    restart: unless-stopped
    networks:
      - spotify-network

networks:
  spotify-network:
    driver: bridge
    external: true
